# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
        - master
  paths:
    exclude:
      - azure-pipelines.yml
      - azure-pipelines-1.yml
      - azure-pipelines-2.yml
      - azure-pipelines-3.yml
      - llvm/utils/lit/lit/msvc_main.py


jobs:
  - job: Regress
    timeoutInMinutes: 420
    pool: 
      name: 'msvc-asan'   
      demands: IsFast
    
    strategy:
      matrix:
        win32_MT_ASAN:
          CRT_FLAG: /MT 
          LINK_LIBS: /wholearchive:%ASAN_RT_LIB_DIR%\clang_rt.asan-i386.lib /wholearchive:%ASAN_RT_LIB_DIR%\clang_rt.asan_cxx-i386.lib
          ASAN_FLAG: /d2ASAN
          ARTIFACT_ID: win32_MT_ASAN
        win32_MD_ASAN:
          CRT_FLAG: /MD 
          LINK_LIBS: /wholearchive:%ASAN_RT_LIB_DIR%\clang_rt.asan_dynamic-i386.lib /wholearchive:%ASAN_RT_LIB_DIR%\clang_rt.asan_dynamic_runtime_thunk-i386.lib
          ASAN_FLAG: /d2ASAN
          ARTIFACT_ID: win32_MD_ASAN
        win32_MT_NOASAN:
          CRT_FLAG: /MT 
          LINK_LIBS: 
          ASAN_FLAG: 
          ARTIFACT_ID: win32_MT_NOASAN
        win32_MD_NOASAN:
          CRT_FLAG: /MD 
          LINK_LIBS: 
          ASAN_FLAG: 
          ARTIFACT_ID: win32_MD_NOASAN
    steps:
    - checkout: none


    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: '0bdbc590-a062-4c3f-b0f6-9383f67865ee'
        pipeline: '11796'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        allowPartiallySucceededBuilds: true
        downloadType: 'single'
        downloadPath: '$(Build.BinariesDirectory)'
        artifactName: llvm_asan_Release_x86_bin

    - task: CmdLine@2
      inputs:
        script: |
            set PATH=%PATH%;$(Build.BinariesDirectory)\llvm_asan_Release_x86_bin\bin;$(Build.BinariesDirectory)\llvm_asan_Release_x86_bin\lib\windows\x86;$(Build.BinariesDirectory)\llvm_asan_Release_x86_bin\include;
            set ASAN_RT_LIB_DIR=$(Build.BinariesDirectory)\llvm_asan_Release_x86_bin\lib\windows\x86
            set ASAN_RT_BIN_DIR=$(Build.BinariesDirectory)\llvm_asan_Release_x86_bin\bin
            echo on
            pushd %MSVC_SRC%
            call %MSVC_SRC%\binaries\x86chk\setenv.cmd x86 %MSVC_SRC%\src
            echo on
            set SKIPENCDIFFS=1
            set _CL_= $(ASAN_FLAG) /Zi $(CRT_FLAG)
            set _LINK_= /debug $(LINK_LIBS) /force:multiple
            pushd %MSVC_SRC%\src\qa\be\regress
            rl -exe -all
            xcopy /i logs  $(Build.ArtifactStagingDirectory)\logs
            popd
            popd
            (exit /b 0)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: $(ARTIFACT_ID)
        publishLocation: 'Container'